server:
  port: 8443
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
        format_sql: true
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
